<?php

namespace Tests\Feature\Views;

use App\Models\Formation;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Category;

class ShowFormationTest extends TestCase
{
    use RefreshDatabase;

    protected $category;
    protected $formation;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category = Category::create([
            'name' => 'category-1',
            'slug' => null
        ]);

        $this->formation = Formation::create([
           'title' => 'Formation 1',
            'resume' => 'long résumé',
            'slug' => null,
            'category_id' => $this->category->id,
            'teaser_path' => 'https://youtube.com/dfjdshfjksdf'
        ]);

    }

    /**
     *
     *
     * @return void
     */
    public function test_show_a_formation()
    {
        //$this->withExceptionHandling();

        $this->get(route('formation.show', [ 'category' => $this->category->slug, 'formation' => $this->formation->slug]))
            ->assertSuccessful()
            ->assertViewIs('public.formation')
            ->assertSee('Formation 1');
    }
}
