<?php

namespace Tests\Feature\Views;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Category;
use App\Models\Formation;

class ShowFormationsListTest extends TestCase
{
    use RefreshDatabase;

    protected $category1, $category2;
    protected $formation1, $formation2, $formation3;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category1 = Category::create([
            'name' => 'category-1',
            'slug' => null
        ]);

        $this->category2 = Category::create([
            'name' => 'category-2',
            'slug' => null
        ]);

        $this->formation1 = Formation::create([
            'title' => 'Titre de Formation 1',
            'resume' => 'long résumé',
            'slug' => null,
            'category_id' => $this->category1->id,
            'teaser_path' => 'https://youtube.com/dfsfsfgh',
            'price' => 40,
        ]);

        $this->formation2 = Formation::create([
            'title' => 'Titre de Formation 2',
            'resume' => 'long résumé',
            'slug' => null,
            'category_id' => $this->category1->id,
            'teaser_path' => 'https://youtube.com/hgfhza',
            'price' => 40,
        ]);

        $this->formation3 = Formation::create([
            'title' => 'Titre de Formation 3',
            'resume' => 'long résumé',
            'slug' => null,
            'category_id' => $this->category2->id,
            'teaser_path' => 'https://youtube.com/oiyzkl',
            'price' => 40,
        ]);
    }

    /**
     * @test
     *
     * @return void
     */
    function test_show_formation_index()
    {
        $this->withoutExceptionHandling();

        $this->get(route('formation.list'))
            ->assertSuccessful()
            ->assertViewIs('public.formation-index');
    }

    /**
     * @test
     *
     * @return void
     */
    function test_show_a_list_of_formations()
    {
        $this->withoutExceptionHandling();

        $this->get(route('formation.category.list', ['category' => $this->category1->slug]))
            ->assertSuccessful()
            ->assertViewIs('public.formation-index')
            ->assertSee('Titre de Formation 1')
            ->assertSee('Titre de Formation 2');

        $this->get(route('formation.list', ['category' => $this->category2->slug]))
            ->assertSuccessful()
            ->assertViewIs('public.formation-index')
            ->assertSee('Titre de Formation 3');
    }
}
