<?php

namespace Tests\Feature\Views;

use App\Models\Category;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ShowArticlesListTest extends TestCase
{
    use RefreshDatabase;

    public $category1;

    public $post1;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category1 = Category::create([
            'name' => 'category 1',
            'slug' => null,
        ]);

        $this->category2 = Category::create([
            'name' => 'category 2',
            'slug' => null,
        ]);

        $this->post1 = $this->category1->posts()->create([
            'title' => 'titre de l\'article numéro 1',
            'text' => 'un text tres long de l\'article numéro 1',
            'slug' => null
        ]);

        $this->post2 = $this->category1->posts()->create([
            'title' => 'titre de l\'article numéro 2',
            'text' => 'un text tres long de l\'article numéro 2',
            'slug' => null
        ]);

        $this->post3 = $this->category2->posts()->create([
            'title' => 'titre de l\'article numéro 3',
            'text' => 'un text tres long de l\'article numéro 3',
            'slug' => null
        ]);
    }

    /**
     * @test
     *
     * @return void
     */
    function test_show_blog_index()
    {
        $this->withoutExceptionHandling();

        $this->get('blog')
            ->assertSuccessful()
            ->assertViewIs('public.post-index');
    }


    /**
     * @test
     *
     * @return void
     */
    function test_show_a_list_of_articles()
    {
        $this->withoutExceptionHandling();

        $this->get('post-index/category:category-1')
            ->assertSuccessful()
            ->assertViewIs('public.post-index')
            ->assertSee('titre de l\'article numéro 1')
            ->assertSee('titre de l\'article numéro 2');

        $this->get('post-index/category:category-2')
            ->assertSuccessful()
            ->assertViewIs('public.post-index')
            ->assertSee('titre de l\'article numéro 3');
    }
}
