<?php

namespace Tests\Feature\Views;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Category;

class ShowArticleTest extends TestCase
{
    use RefreshDatabase;

    public $category1;

    public $post1;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category1 = Category::create([
            'name' => 'cat1',
            'slug' => 'cat1'
        ]);

        $this->post1 = $this->category1->posts()->create([
            'title' => 'titre de l\'article numéro 1',
            'text' => 'un text tres long de l\'article numéro 1',
            'slug' => 'article-1',
        ]);
    }


    /**
     * @test
     *
     * @return void
     */
    function show_an_article()
    {
        $this->withExceptionHandling();

        $this->get('post/article-1')
            ->assertSuccessful()
            ->assertViewIs('public.post');
    }
}
