<?php

namespace Tests\Feature\View;

use App\Models\Chapter;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Formation;
use App\Models\Category;

class ShowChapterTest extends TestCase
{
    use RefreshDatabase;

    protected $category, $formation, $chapter;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category = factory(Category::class)->create();
        $this->formation = factory(Formation::class)->create(['category_id' => $this->category->id]);
        $this->chapter = factory(Chapter::class)->create(['num' => 1, "formation_id" => 1]);
    }

    /**
     *
     *
     * @return void
     */
    public function test_show_a_chapter()
    {
        $this->withExceptionHandling();

        $this->get(route('chapter.show', [
            'category' => $this->formation->category->slug,
            'formation' => $this->formation->slug,
            'chapter' => $this->chapter->slug]
        ))
            ->assertSuccessful()
            ->assertViewIs('public.chapter');
    }
}
