<?php

namespace Tests\Feature\Views;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Category;

class ShowFormationTest extends TestCase
{
    use RefreshDatabase;

    public $category1;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category1 = Category::create([
            'name' => 'category-1',
            'slug' => null
        ]);

    }

    /**
     *
     *
     * @return void
     */
    public function test_show_a_formation()
    {
        //$this->withExceptionHandling();

        $this->get(route('formation', [ 'category' => $this->category1->slug, 'formation' => 'formation-1']))
            ->assertSuccessful()
            ->assertViewIs('public.formation')
            ->assertSee('Formation 1');
    }
}
